import solutions.Day01
import solutions.Day02
import solutions.Day03
import solutions.Day04
import solutions.Day05
import solutions.Day06
import solutions.Day07
import solutions.Day08
import solutions.Day09

fun main(args: Array<String>) {
    println("============================================================================================")
    println("************************************  DAY 01!  *********************************************")
    println("** Day01 Practice Test Case **")
    Day01().practice()
    println("** Day01 Real Test Case **")
    val day1 = Day01()
    println("Part 1 problem is https://adventofcode.com/2022/day/1")
    println("Part 1 solution is ${day1.part01()}")
    println("Part 2 problem is https://adventofcode.com/2022/day/1#part2")
    println("Part 2 solution is ${day1.part02()}")
    println("********************************************************************************************")

    println("************************************  DAY 02!  *********************************************")
    println("** Day02 Practice Test Case **")
    Day02().practice()
    println("** Day02 Real Test Case **")
    val day2 = Day02()
    println("Part 1 problem is https://adventofcode.com/2022/day/2")
    println("Part 1 solution is ${day2.part01()}")
    println("Part 2 problem is https://adventofcode.com/2022/day/2#part2")
    println("Part 2 solution is ${day2.part02()}")
    println("********************************************************************************************")

    println("************************************  DAY 03!  *********************************************")
    println("** Day03 Practice Test Case **")
    Day03().practice()
    println("** Day03 Real Test Case **")
    val day3 = Day03()
    println("Part 1 problem is https://adventofcode.com/2022/day/3")
    println("Part 1 solution is ${day3.part01()}")
    println("Part 2 problem is https://adventofcode.com/2022/day/3#part2")
    println("Part 2 solution is ${day3.part02()}")
    println("********************************************************************************************")

    println("************************************  DAY 04!  *********************************************")
    println("** Day04 Practice Test Case **")
    Day04().practice()
    println("** Day04 Real Test Case **")
    val day4 = Day04()
    println("Part 1 problem is https://adventofcode.com/2022/day/4")
    println("Part 1 solution is ${day4.part01()}")
    println("Part 2 problem is https://adventofcode.com/2022/day/4#part2")
    println("Part 2 solution is ${day4.part02()}")
    println("********************************************************************************************")

    println("************************************  DAY 05!  *********************************************")
    println("** Day05 Practice Test Case **")
    Day05().practice()
    println("** Day05 Real Test Case **")
    val day5 = Day05()
    println("Part 1 problem is https://adventofcode.com/2022/day/5")
    println("Part 1 solution is ${day5.part01()}")
    println("Part 2 problem is https://adventofcode.com/2022/day/5#part2")
    println("Part 2 solution is ${day5.part02()}")
    println("********************************************************************************************")

    println("************************************  DAY 06!  *********************************************")
    println("** Day06 Practice Test Case **")
    Day06().practice()
    println("** Day06 Real Test Case **")
    val day6 = Day06()
    println("Part 1 problem is https://adventofcode.com/2022/day/6")
    print("Part 1 solution is ")
    day6.part01()
    println("Part 2 problem is https://adventofcode.com/2022/day/6#part2")
    print("Part 2 solution is ")
    day6.part02()
    println("********************************************************************************************")

    println("************************************  DAY 07!  *********************************************")
    println("** Day07 Practice Test Case **")
    Day07().practice()
    println("** Day07 Real Test Case **")
    val day7 = Day07()
    println("Part 1 problem is https://adventofcode.com/2022/day/7")
    println("Part 1 solution is ${day7.part01()}")
    println("Part 2 problem is https://adventofcode.com/2022/day/7#part2")
    println("Part 2 solution is ${day7.part02()}")
    println("********************************************************************************************")

    println("************************************  DAY 08!  *********************************************")
    println("** Day08 Practice Test Case **")
    Day08().practice()
    println("** Day08 Real Test Case **")
    val day8 = Day08()
    println("Part 1 problem is https://adventofcode.com/2022/day/8")
    println("Part 1 solution is ${day8.part01()}")
    println("Part 2 problem is https://adventofcode.com/2022/day/8#part2")
    println("Part 2 solution is ${day8.part02()}")
    println("********************************************************************************************")

    println("************************************  DAY 09!  *********************************************")
    println("** Day09 Practice Test Case **")
    Day09().practice()
    println("** Day09 Real Test Case **")
    val day9 = Day09()
    println("Part 1 problem is https://adventofcode.com/2022/day/9")
    println("Part 1 solution is ${day9.part01()}")
    println("Part 2 problem is https://adventofcode.com/2022/day/9#part2")
    println("Part 2 solution is ${day9.part02()}")
    println("********************************************************************************************")
}